csm_response_1 = {
    "perPage": 500,
    "page": 1,
    "total": 750,
    "models": [
        {
            "id": "f77955539b12c48382316ab3923081de",
            "schoolStudentId": "STUDENT_ID",
            "fullName": "John doe",
            "firstName": "John",
            "lastName": "doe",
            "username": "john.doe@calbrightcolle",
            "email": "john.doe@calbrightcollege.org",
            "preferredName": "",
            "permanentEmail": "jd@gmail.com",
            "phone": "(123) 456-9876",
            "accountDisabled": False,
            "accountBlocked": {"id": "0", "label": "Unblocked"},
            "counselors": [
                {
                    "id": "545652b095d0f033f7073404c970a03f",
                    "label": "Rondy Yu",
                    "link": "/api/public/v1/staff/545652b095d0f033f7073404c970a03f",
                }
            ],
            "majors": [{"id": "0160", "label": "IT Support"}],
            "minors": [],
            "certificates": [],
            "schools": [],
            "graduationDate": None,
            "gpa": None,
            "degreeLevel": None,
            "classLevel": None,
            "workAuthorization": None,
            "programType": [],
            "applicantType": [{"id": "1", "label": "Current Student"}],
            "languageProficiencies": [],
            "proNetProfile": None,
            "address": {
                "id": "7e6c31245e0f448b639221d2d4c8ce91",
                "label": "123 S Anytown Dr\nMadera, California 93637\nUnited States",
                "link": "/api/public/v1/addresses/7e6c31245e0f448b639221d2d4c8ce91",
            },
            "permanentAddress": None,
            "hasApprovedResume": False,
            "lastLogin": None,
            "advocateIncidentHistory": None,
            "advocateCareHistory": None,
            "accommodateAccessibility": None,
            "lastModified": "2024-04-13T00:23:18Z",
            "customFields": {
                "county_of_residence": "Madera",
                "mobile_phone_number": "(567) 123-5420",
                "fg_generated_382363": "",
                "email_opt_out": "0",
                "sms_opt_out": "0",
                "do_not_call": "0",
                "calbright_programs_completed": [],
                "current_end_term_date": "2024-06-03",
                "portfolio": "",
                "international_student": None,
                "first_generation_college_stude": None,
                "enrollment_status": {"id": "5", "label": "Started Program Pathway"},
                "last_term_enrolled": None,
                "date_of_enrollment": "2023-11-30",
                "leave_start_date": None,
                "leave_end_date": None,
                "most_recent_certificate_comple": None,
                "current_program": "",
            },
        }
    ],
}

expected_response_1 = {
    "id": "f77955539b12c48382316ab3923081de",
    "schoolStudentId": "STUDENT_ID",
    "fullName": "John doe",
    "firstName": "John",
    "lastName": "doe",
    "username": "john.doe@calbrightcolle",
    "email": "john.doe@calbrightcollege.org",
    "permanentEmail": "jd@gmail.com",
    "phone": "(123) 456-9876",
    "accountDisabled": False,
    "accountBlocked": "0",
    "counselors": ["545652b095d0f033f7073404c970a03f"],
    "majors": ["0160"],
    "applicantType": ["1"],
    "address": {"street": "123 S Anytown Dr", "city": "Madera", "state": "US-CA", "zip": "93637", "country": "US"},
    "county_of_residence": "Madera",
    "mobile_phone_number": "(567) 123-5420",
    "email_opt_out": False,
    "sms_opt_out": False,
    "do_not_call": False,
    "current_end_term_date": "2024-06-03",
    "enrollment_status": "5",
    "date_of_enrollment": "2023-11-30",
}

csm_response_2 = {
    "perPage": 500,
    "page": 2,
    "total": 750,
    "models": [
        {
            "id": "f77955539b12c48382316ab3923081de",
            "label": "Calbright Student",
            "schoolStudentId": "STUDENT_ID_2",
            "fullName": "Calbright student",
            "firstName": "Calbright",
            "middleName": "",
            "lastName": "student",
            "username": "calbright.student@calbrightcolle",
            "email": "calbright.student@calbrightcollege.org",
            "preferredName": "",
            "gender": None,
            "permanentEmail": "calbstudent@gmail.com",
            "phone": "(123) 456-9876",
            "birthdate": None,
            "alum": False,
            "accountDisabled": False,
            "status": [],
            "accountBlocked": {"id": "0", "label": "Unblocked"},
            "counselors": [
                {
                    "id": "545652b095d0f033f7073404c970a03f",
                    "label": "Rondy Yu",
                    "link": "/api/public/v1/staff/545652b095d0f033f7073404c970a03f",
                }
            ],
            "majors": [{"id": "0160", "label": "IT Support"}],
            "minors": [],
            "certificates": [],
            "schools": [],
            "graduationDate": None,
            "gpa": None,
            "degreeLevel": None,
            "classLevel": None,
            "workAuthorization": None,
            "programType": [],
            "applicantType": [{"id": "1", "label": "Current Student"}],
            "languageProficiencies": [],
            "proNetProfile": None,
            "address": {
                "id": "7e6c31245e0f448b639221d2d4c8ce91",
                "label": "543 S Main St Dr\nMadera, California 93637\nUnited States",
                "link": "/api/public/v1/addresses/7e6c31245e0f448b639221d2d4c8ce91",
            },
            "permanentAddress": None,
            "hasApprovedResume": False,
            "lastLogin": None,
            "advocateIncidentHistory": None,
            "advocateCareHistory": None,
            "accommodateAccessibility": None,
            "lastModified": "2024-04-13T00:23:18Z",
            "customFields": {
                "county_of_residence": "Madera",
                "mobile_phone_number": "(567) 123-5420",
                "fg_generated_382363": "",
                "email_opt_out": "0",
                "sms_opt_out": "0",
                "do_not_call": "0",
                "calbright_programs_completed": [{"id": "040"}],
                "current_end_term_date": "2024-06-03",
                "portfolio": "",
                "international_student": None,
                "first_generation_college_stude": None,
                "enrollment_status": {"id": "3", "label": "Completed Program Pathway"},
                "last_term_enrolled": "2023-11-30",
                "date_of_enrollment": "2023-11-30",
                "leave_start_date": "2023-11-30",
                "leave_end_date": "2023-11-30",
                "most_recent_certificate_comple": "2023-11-30",
                "current_program": "",
            },
        }
    ],
}

expected_response_2 = {
    "id": "f77955539b12c48382316ab3923081de",
    "schoolStudentId": "STUDENT_ID_2",
    "fullName": "Calbright student",
    "firstName": "Calbright",
    "lastName": "student",
    "username": "calbright.student@calbrightcolle",
    "email": "calbright.student@calbrightcollege.org",
    "permanentEmail": "calbstudent@gmail.com",
    "phone": "(123) 456-9876",
    "accountDisabled": False,
    "accountBlocked": "0",
    "counselors": ["545652b095d0f033f7073404c970a03f"],
    "majors": ["0160"],
    "applicantType": ["1"],
    "address": {"street": "543 S Main St Dr", "city": "Madera", "state": "US-CA", "zip": "93637", "country": "US"},
    "county_of_residence": "Madera",
    "mobile_phone_number": "(567) 123-5420",
    "email_opt_out": False,
    "sms_opt_out": False,
    "do_not_call": False,
    "calbright_programs_completed": ["040"],
    "current_end_term_date": "2024-06-03",
    "enrollment_status": "3",
    "last_term_enrolled": "2023-11-30",
    "date_of_enrollment": "2023-11-30",
    "leave_start_date": "2023-11-30",
    "leave_end_date": "2023-11-30",
    "most_recent_certificate_comple": "2023-11-30",
}
