from configurations.constants import (
    SSM_CALBRIGHT_PROD_WRITE,
    SSM_CONSTANTS_PROD,
    SSM_FEATURE_FLAGS_PROD,
    SSM_SALESFORCE_PROD,
    SSM_GDRIVE,
    SSM_HUBSPOT,
    SSM_CALENDLY,
    SSM_IRONIKUS_PROD,
    PANDADOC_PROD,
    PROD_VS_INTAKE_EMAIL,
    CSEP_COMPLETE_EMAIL_ID,
    PROD_GDRIVE_VS_PARENT_FOLDER,
    SSM_SLACK,
    SSM_GSHEETS_STUDENTS,
    SSM_GSHEETS_SVC_ENGINEERING,
    SSM_GSUITE_SVC_ENGINEERING_LICENSING,
    SSM_GEOLOCATOR_STAGE,
    SSM_STRUT_PROD,
    PROD_SHEET_KEYS_MAP,
    SSM_TANGOE_PROD,
    CSEP_DEVICE_REQUEST_EMAIL_ID,
    SSM_CANVAS,
)

prod_configs = {
    # ssm
    "calbright_write_ssm": SSM_CALBRIGHT_PROD_WRITE,
    "constants": SSM_CONSTANTS_PROD,
    "feature_flags": SSM_FEATURE_FLAGS_PROD,
    "salesforce_ssm": SSM_SALESFORCE_PROD,
    "gdrive_ssm": SSM_GDRIVE,
    "hubspot_ssm": SSM_HUBSPOT,
    "calendly_ssm": SSM_CALENDLY,
    "slack_ssm": SSM_SLACK,
    "wpwh_ssm": SSM_IRONIKUS_PROD,
    "pandadoc_ssm": PANDADOC_PROD,
    "gsheets_ssm": SSM_GSHEETS_STUDENTS,
    "gsheets_svc_ssm": SSM_GSHEETS_SVC_ENGINEERING,
    "gsuite_svc_ssm": SSM_GSUITE_SVC_ENGINEERING_LICENSING,
    "geolocator_ssm": SSM_GEOLOCATOR_STAGE,
    "strut_ssm": SSM_STRUT_PROD,
    # Event Specific configurations
    "csep_complete": {
        "veteran_services_intake_request_id": PROD_VS_INTAKE_EMAIL,
        "csep_complete_email_id": CSEP_COMPLETE_EMAIL_ID,
        "csep_device_request_email_id": CSEP_DEVICE_REQUEST_EMAIL_ID,
    },
    "veteran_intake_complete": {"g_drive_parent_folder": PROD_GDRIVE_VS_PARENT_FOLDER},
    "form_bucket": "calbright-students",
    "gsheets_keys": PROD_SHEET_KEYS_MAP,
    "tangoe_ssm": SSM_TANGOE_PROD,
    "canvas_ssm": SSM_CANVAS,
    "override_canvas": False,
    "canvas_orientation_section": 275,
}
