from configurations.constants import (
    SSM_CALBRIGHT_STAGE_WRITE,
    SSM_CONSTANTS_STAGE,
    SSM_FEATURE_FLAGS_STAGE,
    SSM_SALESFORCE_STAGE,
    SSM_GDRIVE,
    SSM_GSHEETS_STUDENTS,
    SSM_GSHEETS_SVC_ENGINEERING,
    SSM_GSUITE_SVC_ENGINEERING_LICENSING,
    SSM_SLACK,
    SSM_GEOLOCATOR_STAGE,
    SSM_HUBSPOT,
    SSM_CALENDLY,
    PANDADOC_SANDBOX,
    STAGE_VS_INTAKE_EMAIL,
    CSEP_COMPLETE_EMAIL_ID,
    STAGE_GDRIVE_VS_PARENT_FOLDER,
    SSM_IRONIKUS_BETA,
    STAGE_SHEET_KEYS_MAP,
    SSM_STRUT_PROD,
    SSM_TANGOE_STAGE,
    CSEP_DEVICE_REQUEST_EMAIL_ID,
    SSM_CANVAS_STAGE,
)

stage_configs = {
    # ssm
    "calbright_write_ssm": SSM_CALBRIGHT_STAGE_WRITE,
    "constants": SSM_CONSTANTS_STAGE,
    "feature_flags": SSM_FEATURE_FLAGS_STAGE,
    "salesforce_ssm": SSM_SALESFORCE_STAGE,
    "gdrive_ssm": SSM_GDRIVE,
    "hubspot_ssm": SSM_HUBSPOT,
    "calendly_ssm": SSM_CALENDLY,
    "slack_ssm": SSM_SLACK,
    "wpwh_ssm": SSM_IRONIKUS_BETA,
    "gsheets_ssm": SSM_GSHEETS_STUDENTS,
    "gsheets_svc_ssm": SSM_GSHEETS_SVC_ENGINEERING,
    "gsuite_svc_ssm": SSM_GSUITE_SVC_ENGINEERING_LICENSING,
    "geolocator_ssm": SSM_GEOLOCATOR_STAGE,
    "strut_ssm": SSM_STRUT_PROD,
    "pandadoc_ssm": PANDADOC_SANDBOX,
    # Event Specific configurations
    "csep_complete": {
        "veteran_services_intake_request_id": STAGE_VS_INTAKE_EMAIL,
        "csep_complete_email_id": CSEP_COMPLETE_EMAIL_ID,
        "csep_device_request_email_id": CSEP_DEVICE_REQUEST_EMAIL_ID,
    },
    "veteran_intake_complete": {"g_drive_parent_folder": STAGE_GDRIVE_VS_PARENT_FOLDER},
    "form_bucket": "calbright-engineering",
    "gsheets_keys": STAGE_SHEET_KEYS_MAP,
    "tangoe_ssm": SSM_TANGOE_STAGE,
    "canvas_ssm": SSM_CANVAS_STAGE,
    "override_canvas": True,
    "canvas_orientation_section": 31,
}
